### ISSUE TITLE
Does not work with Godot 4.1

### ISSUE THREAD

**Issue by Paraldos** [mrsir8433/godot_shaders#1]
Hey there,

i love the shader and used it before in a project of mine. While I am trying to convert the project to Godot 4.1 i noticed the shader is no longer working.
Shaders really are my wekpoint, so i hoped you could adapt it for the new version :)

**Comment by Paraldos** [comment]
![shader](https://github.com/biswas08433/godot_shaders/assets/54956252/bf2db20b-24c8-4ed7-aa65-2103cc945dbd)

**Comment by biswas08433** [comment]
Sorted

**Comment by Paraldos** [comment]
Worked like a charm. Thanks for the help

Result is a bit hard to see in the gif, but its a great effect adding to the players warpjump.
![Warpjump3](https://github.com/biswas08433/godot_shaders/assets/54956252/c19904e6-bf72-4bf6-9b87-7c65b15a30c0)
